### ISSUE TITLE
Unexpected warning when URL of server object is relative URL

### ISSUE THREAD

**Issue by VcamX** [swagger-api/swagger-parser#1509]
```
severs:
  - url: /v1
```
In `SwaggerParseResult`, I saw message "attribute .servers. invalid url: /v1 ".

Wonder if relative URL is not supported anymore.

Thanks!

**Comment by VcamX** [comment]
@gracekarina

**Comment by VcamX** [comment]
From [OpenAPI specs](https://spec.openapis.org/oas/v3.0.3#fixed-fields-3) and [Swagger doc](https://swagger.io/specification/#server-object):
> REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.

Found the related PR is #1301 and it's introduced since [v2.0.18](https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.18). There's also a change in #1412 for [RelativeReferenceTest](https://github.com/swagger-api/swagger-parser/pull/1412/files#diff-19d61f466b4ffad87fd7a6aaf58700054739e038cfa98aa59a835ca15ceb737dR31). It replaced the **relative** URL with absolute URL.

**Comment by r-sreesaran** [comment]
The changes has been rolled back. 
please do check  https://github.com/swagger-api/swagger-parser/issues/1329
Also do try with the latest version of parser.

**Comment by VcamX** [comment]
> The changes has been rolled back.
> please do check #1329
> Also do try with the latest version of parser.

Thanks for your reply!

The issue doesn't seem to be resolved. I tried with latest release v2.0.24 but still saw the warning. A similar issue is also mentioned on https://github.com/swagger-api/swagger-parser/issues/1329#issuecomment-734399969

I don't see any error/exception but this warning actually. So the point (i think) is if the warning here is appropriate: https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L429
Based on OpenAPI specs and Swagger doc, the URL `/` is valid. And the warning is put into parsing result  `SwaggerParseResult`. This can be misleading imho.

**Comment by r-sreesaran** [comment]
As you said having relative url is valid and it should not throw an error. I will raise a pr with fix and test for the same.

**Comment by boagm** [comment]
Hi

I think I'm also hitting this issue, when I grab https://petstore3.swagger.io/api/v3/openapi.json which has

`    servers  url | "/api/v3"`

and I parse it via

```
      ParseOptions options = new ParseOptions();
      options.setResolve(true);
      options.setResolveFully(true);
      SwaggerParseResult res = openAPIV3Parser.readLocation(docPath,null, options);

```
with swagger-parser-v3-2.0.24.jar `res.getMessages()` shows       `String index out of range: 0`
and `res.getOpenAPI()` is `null`.

If I rollback back to swagger-parser-v3-2.0.17.jar, we're all good.

Thanks

**Comment by gracekarina** [comment]
Hi, @boagm, @VcamX , I have tested with current snapshot of Swagger-Parser, and this is not an issue, I will commit a test to show you. 
Thanks for reporting this.

**Comment by VcamX** [comment]
@gracekarina Thanks for your reply! Have you tried with local OpenAPI schema file instead of the one is served on the server? In my use case I have to package the schema file in jar.
@boagm wonder if you put the schema file in jar or on a remote location.

**Comment by VcamX** [comment]
I guess the folks here https://github.com/OpenAPITools/openapi-generator/issues/8266 also used local schema file to do codegen

**Comment by gracekarina** [comment]
Hi @VcamX , Which version of parser is being used?

**Comment by VcamX** [comment]
> Hi @VcamX , Which version of parser is being used?

I tried both 2.0.24 and 2.0.18 but they didn't work, but 2.0.17 has no issue as @boagm mentioned.


> From [OpenAPI specs](https://spec.openapis.org/oas/v3.0.3#fixed-fields-3) and [Swagger doc](https://swagger.io/specification/#server-object):
> 
> > REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.
> 
> Found the related PR is #1301 and it's introduced since [v2.0.18](https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.18). There's also a change in #1412 for [RelativeReferenceTest](https://github.com/swagger-api/swagger-parser/pull/1412/files#diff-19d61f466b4ffad87fd7a6aaf58700054739e038cfa98aa59a835ca15ceb737dR31). It replaced the **relative** URL with absolute URL.

I suspect the issue exists since 2.0.18.

**Comment by gracekarina** [comment]
@VcamX, as I have tested locally, I could only reproduced the issue in 2.0.18, the following versions does not have the issue. So I kindly ask you to attach here the spec you are using, or a small sample orfthe jar being use so I can reproduce the issue and help fixed it. Thank you.

**Comment by boagm** [comment]
Hi @gracekarina,

Thanks for adding the testcase #1519 , it has enabled me to figure what is the difference that leads to me still hitting the issue with swagger-parser-v3-2.0.24.jar res.getMessages() shows "_String index out of range: 0_" and "res.getOpenAPI() is null" when parsing the OpenAPI from https://petstore3.swagger.io/api/v3/openapi.json, which has
 ```
 servers:
    url: "/api/v3"

```
   
In your testcase you have 
`  String url = "https://petstore3.swagger.io/api/v3/openapi.json";
So after parsing the server POJ has `Servers.url: https://petstore3.swagger.io/api/v3`

While in my case the OpenAPI is already downloaded and on local file system so in I have
`  String url = "c:\\temp\\petstore3.swagger.io\\api\\v3\\openapi.json";`

Now of cause the spec https://swagger.io/docs/specification/api-host-and-base-path/ says
  _"If the server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted"_

I note @VcamX  said _"In my use case I have to package the schema file in jar."_  I wonder what is passed as arg0 to `io.swagger.v3.parser.OpenAPIV3Parser.readLocation()` in that case?


So what does "relative" mean for a location on a filesystem? 

Interestingly I then tried using:
`  String url = "file:///c:/temp/petstore3.swagger.io/api/v3/openapi.json";`
and found that this does avoid the "_String index out of range: 0_"  issue. 
In this case of a file url the parsed POJ model gives the unmodified relative path:-
  `Servers.url: /api/v302`


For my use case I could switch to using a file URL rather than a path, but I do think it's rather inconsistent behavour here, so would appropriate you thoughts?

Thanks
   Martin

**Comment by gracekarina** [comment]
Hi, @VcamX, @boagm, I added here two tests to try to reproduce the issues here exposed, but I was not able to reproduce them. 
As I see it, there are two situations:
1.  In SwaggerParseResult, the message "attribute .servers. invalid url: /v1 ". This validation was removed since 2.0.19 and nexts releases do not show the message.
2. res.getMessages() shows String index out of range: 0 and res.getOpenAPI() is null. This issue I have not been able to reproduce.

Thanks for your comments. Please check the commits and if you have an spec, or a sample with the issue reproduced please attach it to a new issue and metion this one.

**Comment by boagm** [comment]
Thanks @gracekarina,

As per my comment on your "testServerRelativeUrlLocal", we're getting close, but I'd not realized another subtlety .. to reproduce  the "String index out of range: 0" we need to be passing an absolute path,  just "openapilocal.json" did not reproduce the issue - while "C:\devel\test\openapilocal.json" does.

Thanks
   Martin

**Comment by VcamX** [comment]
@gracekarina for my case, I was using relative path like `schema/openapi.yml` as schema file path.
wonder if it's necessary use the path of schema file to determine the URL of server: https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L421

**Comment by gracekarina** [comment]
@VcamX please attach your case here.
