### ISSUE TITLE
Cannot pull in $ref stuff from classpath

### ISSUE THREAD

**Issue by sohrab-** [swagger-api/swagger-parser#249]
Looking at [the code](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java#L131), it should already support classpath URL resolution but it is not working for me. I am not sure if it is a bug or if I am not using it correctly.

To demonstrate the problem, I have put this repo together: https://github.com/sohrab-/swagger-classpath-ref

In there, I have a `common` project and a `service` project, that depends on `common`. The Swagger YAML file in `service` attempts to pull a parameter which is defined in `common` but with little success. The file is definitely there in the `common-1.0.jar`.

To replicate my issue, do a `mvn clean install` in the `common` directory first. Then try `mvn clean install` in the `service` directory. It'll fail with

```
Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.1.6:generate (default) on project service: Execution default of goal io.swagger:swagger-codegen-maven-plugin:2.1.6:generate failed: Unable to load RELATIVE ref: ./parameters.yaml: Could not find ./parameters.yaml on the classpath
```

It looks like it is falling through everything and land on this line: https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/ClasspathHelper.java#L31

I have tried different variations of the URL, e.g. without `./` or with `/`, but no dice.

Obviously if you copy `common/src/main/resources/parameters.yaml` into `service/src/main/resources`, then it all works. But my goal is to keep the common stuff in their own project.

_This was originally raised on Swagger forum: https://groups.google.com/forum/#!topic/swagger-swaggersocket/4IRAVFCOvPk_

**Comment by timdvail** [comment]
Hey -- I think you can solve this issue by changing the pom.xml -- in the plugin section, add a dependency like this:
        <plugin>
          <groupId>io.swagger</groupId>
          <artifactId>swagger-codegen-maven-plugin</artifactId>
          <version>2.1.6</version>
          <dependencies>
            <dependency>
                <groupId>com.github.sohrab</groupId>
                <artifactId>common</artifactId>
                <version>1.0</version>
            </dependency>
          </dependencies>
....
</plugin>

The issue here is when you use the swagger-codegen-maven-plugin -- maven plugins cannot see classes in the project dependencies unless you explicitly add it as a dependency for the plugin itself.  You will need to change the reference from './parameters.yaml' to '/parameters.yaml'.  I think in the case of './parameters.yaml' the parser looks in the working directory of the yaml file (which technically is not in the classpath) for the file.  I don't think it really used the classpath in the first place in resolving ./parameters.yaml.

**Comment by sohrab-** [comment]
Sorry for the late reply (we somehow managed to do this snail-mail-style) but your suggestion definitely resolves the issue. I did end up doing something similar in Gradle to get over this. I have updated my repo with your suggestion as well. Thank you!
