### ISSUE TITLE
Parser validation

### ISSUE THREAD

**Issue by ArulPrakas** [swagger-api/swagger-parser#46]
Is there a way to validate the provided source file and report its warning/errors? Currenlty new SwaggerParser().read() just returns null if parser unable to load the file. Is there a way to return the error while loading the swagger file?

**Comment by RobWin** [comment]
+1

**Comment by fehguy** [comment]
Possibly so.  There are some decisions made when parsing JSON specs that cause it to abandon.  For example, if the version isn't "2.0", the 2.0 spec parser will simply quit.  I am sure we can add more information but I'm expecting it will be bundled up in an exception rather than a processing report.  Would that suffice?

**Comment by RobWin** [comment]
Yes.

**Comment by guptasu** [comment]
+1 for this feature. Currently I am doing Schema validation before using SwaggerParser().read(). It will be nice if this is part of the parser code.

**Comment by fehguy** [comment]
Please see here, there is a new method that exposes human-readable feedback:

https://github.com/swagger-api/swagger-parser/issues/108

Also see tests here:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/test/java/io/swagger/parser/util/SwaggerDeserializerTest.java
