### ISSUE TITLE
Path doesn't contain parameters after deserialization

### ISSUE THREAD

**Issue by giuliopulina** [swagger-api/swagger-parser#545]
Hello,

I'm trying to read defined path parameters from Path object after deserialization, but I found out that the list is always null.
In fact, path params are set to null at this line:

https://github.com/swagger-api/swagger-parser/blob/e3d545b7e4cd20553023ad77a7298b0fc46a4a0e/modules/swagger-parser/src/main/java/io/swagger/parser/processors/PathsProcessor.java#L74

Can you clarify why this 'reset' is done?

Thanks
Giulio

**Comment by gracekarina** [comment]
Hi, Can you provide the spec you are testing this with?
Thanks 👍

**Comment by gracekarina** [comment]
@giuliopulina The list will always be null because, the pathProcessor has "shared" parameters, so when the paths are being processed the processor sets the parameters into each of the defined operations inside the path Object. So without looking at the spec I say (maybe I'm mistaken) if you need the parameters you should look inside one of the operation of that path Object. It should have them. Please send us the spec to look further.

**Comment by giuliopulina** [comment]
@gracekarina I think that, writing this issue, I didn't understand well what Path.getParameters() was meant to return. 
I was trying to read the defined path parameters for a given path (in order to perform semantic validation): let's we have a path like:

/users/{id}/addresses/{addressId}

I was expecting to get two PathParam ("id" and "addressId") from the Path object.

After your explanation (and after reading about 'shared parameters' in the doc, I'm not using them in my spec) I understood that for my use case, I can simply parse the path string and extract param from there.

Thank you a lot, I think the issue can be closed.
