### ISSUE TITLE
Vendor extensions not populated for RefProperty

### ISSUE THREAD

**Issue by joostfarla** [swagger-api/swagger-parser#666]
When using a `$ref` schema, vendor extensions are not populated. Example configuration:

```
responses:
  200:
    description: OK
      schema:
        $ref: "#/definitions/Foo"
        x-foo: bar
```

`RefProperty::getVendorExtensions()` now returns an empty map. I would expect the `x-*` properties to be added as vendor extensions on the `RefProperty` object.

**Comment by webron** [comment]
Unfortunately for you, you got to open ticket #666, which means we have to close it a soon as possible as it's practically the gates to hell (😈). 

Seriously though - you shouldn't expect the extensions to be added to the RefProperty object. By definition, references do not allow additional properties, whether they are extensions or not is irrelevant. Anything you put next to it, would end up being ignored. It's not us, it's how the JSON Reference specification defines it. Completely understand why it's inconvenient, but that's one of the limitations of the spec.

**Comment by webron** [comment]
However, since the devil is in the details - we might actually be able to support something like that, but it would be easier with the new version of the parser that supports OAS3. We might be able to add a parameter that would keep adjacent properties to a ref untouched, to allow for such processing, even if it is technically not valid. Would that be of interest to you?

**Comment by joostfarla** [comment]
@webron Thanks for the quick response! That would definitely be interesting! We use vendor extensions a lot, because they map the spec to our code. Because a definition can be referenced from multiple places, we want to be able to change its "scope" by using an extension on the `$ref` level.

**Comment by krraghavan** [comment]
@webron I see that this issue is closed.  Does that mean you won't be fixing it?  I have a use case for generating proto definitions from these YAML files and am using these extension fields to provide codegen hints (specifically the number mapping which I must do for references as well).   For example:

`
KVStringPair:
  type: object
  properties:
    key:
      type: string
      x-codegen-hint:
        proto:
          - type: proto-index
            properties:
              index: 1003
    value:
      $ref:  "#/components/schemas/ValueSchema"
      x-codegen-hint:
        proto:
          - type: proto-index
            properties:
              index: 1004
              # this codegen hint will be ignored`

# ValueSchema not shown

**Comment by krraghavan** [comment]
@webron I have a PR that I am able to submit for this.  Would you be willing to consider it?

**Comment by webron** [comment]
@frantuma - thoughts about the above comment?
