### ISSUE TITLE
Conversion v1.2 to v2: type "any" gets converted as reference

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-parser#803]
Discovered during review of https://github.com/swagger-api/swagger-parser/pull/801.

Take as input: [issue799.json](https://github.com/swagger-api/swagger-parser/blob/75d060d9ae8e617191fe8a2fc1376c9f4a7d2eb3/modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/issue799.json)

Convert it to Swagger 2.0 format (`io.swagger.converter.LegacyConverterTest.testIssue799()` with `Json.prettyPrint(swagger);` can be used for that).

Paste the result to http://editor.swagger.io/ you get 2 errors:

> Semantic error at definitions.v1beta3.ObjectMeta.properties.annotations.$ref
$refs must reference a valid location in the document
Jump to line 149
Semantic error at definitions.v1beta3.ObjectMeta.properties.labels.$ref
$refs must reference a valid location in the document
Jump to line 165
 
This is because:
https://github.com/swagger-api/swagger-parser/blob/75d060d9ae8e617191fe8a2fc1376c9f4a7d2eb3/modules/swagger-compat-spec-parser/src/test/resources/specs/v1_2/issue799.json#L273-L276

Is converted to:

```json
          "$ref" : "#/definitions/any"
```

My guess is that this should be converted an object model (and then to an `object` schema in OAS3).

**Comment by webron** [comment]
The conversion works as expected. `any` is not a valid primitive type in 1.2 (or any other version for that matter), and it's being interpreted as a model name instead because that's what the spec says it will be. Not having such a model definition, it ends up being invalid.

The solution can't be to convert it to an object model, because we can't really tell what the author intended. The solution is to fix the definition and make it valid.

**Comment by jmini** [comment]
Thank you for the analysis... 

If the `1.2` spec is already invalid, you can only get an invalid converted spec. It makes sense to me.
