### ISSUE TITLE
Deprecated field in Schemas Object must be set to false by default

### ISSUE THREAD

**Issue by r-sreesaran** [swagger-api/swagger-parser#922]
By specification :
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject

"Specifies that a schema is deprecated and SHOULD be transitioned out of usage. default value is false"

The default value needs to be set as false for all schema, but currently, it is not initialized.

**Comment by r-sreesaran** [comment]
I have raised a PR for the issue.

**Comment by gracekarina** [comment]
Closed By #923

**Comment by frantuma** [comment]
@r-sreesaran #950 reverts #933 as according to the spec, `deprecated` is an optional property, which defaults to `false` when not specified; this doesn't mean that it must be explicitly set to `false`, and I would say it's not desired to have the parser explicitly set to their default values all optional properties with a default value in spec (at least not as default, will open a new ticket to activate this behaviour with options flag); please let me know if you still think we should maintain this behaviour as standard instead of activated via an option.
The main drawback of the reverted behaviour is the "pollution" of the spec e.g with mass `deprecated = false` fields, also it slightly changes the original spec (non present properties -> properties with default values) which again I don't feel should be the default behaviour

**Comment by r-sreesaran** [comment]
@frantuma understood your point, that seems to be valid. Thanks for reverting the changes.
